### ISSUE TITLE
Login con SPID

### ISSUE THREAD

**Issue by nferruzzi** [italia/design-ui-kit#1]
Ciao,
non mi pare sia presente il simbolo per un bottone di login "ufficiale" da usare per SPID 
tipo quello mostrato qua per dire
https://www.spid.gov.it/assets/img/home/riconosci_spid.svg

graziee

**Comment by nikorobins** [comment]
Ciao,
è possibile costruire il bottone SPID prendendo come base il "button primary"  cambiare il colore di sfondo (blu 50) e aggiungere il logo di spid presente tra i simboli. Ad ogni modo per facilitare la questione posso aggiungerlo alla "page". 
Grazie a te per l'interessamento :-)

**Comment by nferruzzi** [comment]
grazie!

**Comment by umbros** [comment]
Ciao, in realtà il bottone SPID è un widget quindi correttissimo come dice Dani nel momento in cui si vuole mettere un pulsante SPID senza selezione degli Identity Provider, per l'utilizzo canonico questo è l'attuale bottone: https://github.com/italia/spid-sp-access-button anche se per nuove implementazioni ti chiedo di pazientare la settimana prossima che verrà rilasciata la nuova versione.

**Comment by AlessandroVecchi** [comment]
ciao,
è passato un po' di tempo...
resta valido questo come elemento ufficiale? https://github.com/italia/spid-sp-access-button/tree/master/src/development

c'è anche nel web toolkit https://italia.github.io/design-web-toolkit/components/detail/spid.html ma estrapolarlo come componenete singolo è un po' scomodo

**Comment by nikorobins** [comment]
Ciao Alessandro,
bentornato! Per SPID stiamo sviluppando uno smart button che trovi qui https://github.com/italia/spid-smart-button (c'è anche un mockup in html puro). In questo repo invece, se possono esserti utili, ho appena caricato le guidelines UX/UI sull'uso del logo e del bottone SPID. In generale il toolkit a cui fai riferimento non verrà più implementato ed è sostituito da Bootstrap Italia https://italia.github.io/bootstrap-italia/.

**Comment by AlessandroVecchi** [comment]
Ciao, Daniela,
è parecchio che è in sviluppo lo smart button, si sa più o meno quando sarà reso disponibile?
