### ISSUE TITLE
Grid system: update the grid styles

### ISSUE THREAD

**Issue by zetareticoli** [italia/design-ui-kit#104]
### Does a discussion already exist on the topic you are interested in, or on a similar topic?

- [X] I verified and it doesn't exist

### What

The grid styles included in the UI kit are meant for fixed-size container width (see[ Bootstrap Italia docs](https://italia.github.io/bootstrap-italia/docs/organizzare-gli-spazi/introduzione/#contenitori)). We should specify that and add the fluid container case.

#### To do

- [x] update grid styles for fixed-size container
- [x] add grid style for fluid container
- [x] update grid documentation
- [ ] add link to official Design system [docs]((https://designers.italia.it/design-system/fondamenti/griglia/))

### Why

The grid styles, as-is, could be misused or misunderstood.

**Comment by Fupete** [comment]
Just published the fix in v3.3. Tx @zetareticoli for the great work.
