### ISSUE TITLE
http://www.imxprs.com/free/kybertech/italia_designers

### ISSUE THREAD

**Issue by ValentinoDesigner** [italia/design-ui-kit#105]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Questo è il sito web creato da me con le stesse caratteristiche info moduli e links! [

](http://www.imxprs.com/free/kybertech/italia_designers)

### Perché

Come inserisco il codice su GitHub c’è una pagina. Di caricamento links? È completo!

### Contesto

https://designers.italia.it/community/eventi/20231128-realizzare-interfacce-pubbliche-di-qualita-e-piu-accessibili-grazie-al-design-system-del-paese/

### Altro

Grazie

**Comment by ValentinoDesigner** [comment]
Chi mi aiuta? Grz Valentino Designer - Kief Studio Agency Bari

**Comment by Fupete** [comment]
Ciao @ValentinoDesigner. La pagina "creata da te" linkata sopra nella issue risulta vuota/bianca. Puoi condividerla in altro modo?

**Comment by ValentinoDesigner** [comment]
tramite indirizzo web url che compare nel prompt


Il giorno gio 7 dic 2023 alle ore 12:39 stale[bot] ***@***.***>
ha scritto:
