### ISSUE TITLE
We need to update Megamenu component

### ISSUE THREAD

**Issue by Fupete** [italia/design-ui-kit#107]
### Does a discussion already exist on the topic you are interested in, or on a similar topic?

- [X] I verified and it doesn't exist

### What

As we are doing in Bootstrap Italia (https://github.com/italia/bootstrap-italia/issues/995) we need to upgrade our Megamenu component to the standard of the one we design and develop for Designers Italia website. 

### Why

- Be fully A11y compliant. 
- Be in sync with Bootstrap Italia.

**Comment by zetareticoli** [comment]
I've crafted a new version based on the [revised component](https://github.com/italia/bootstrap-italia/pull/1025) in Bootstrap Italia.

Preview available here: https://www.figma.com/file/2gaQw683ZazAPEILQtFLZF/%5BDesign-system-%E2%80%A8del-Paese%5D---UI-Kit-Italia?type=design&node-id=4022%3A304243&mode=design&t=hNN7pczfIFmX8q1C-1

**Comment by Fupete** [comment]
Just published in v3.3. Tx @zetareticoli for the great work.
