### ISSUE TITLE
component `Link` - variant disabled with typo

### ISSUE THREAD

**Issue by steps88** [italia/design-ui-kit#122]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Quando si usa il componente LINK nel suo stato disabilitato, il menu delle varianti mostra 2 alternative 'Disabled' 'disabled'
<img width="613" alt="image" src="https://github.com/italia/design-ui-kit/assets/91465481/873decf6-7232-49e1-afea-49a82855f297">

### Perché

Crea confusione

**Comment by Fupete** [comment]
Fixed in [[v3.4.0](https://github.com/italia/design-ui-kit/releases/tag/v3.4.0)]
