### ISSUE TITLE
Megamenu items space

### ISSUE THREAD

**Issue by zetareticoli** [italia/design-ui-kit#128]
### Does a discussion already exist on the topic you are interested in, or on a similar topic?

- [X] I verified and it doesn't exist

### What

The space between nav items with megamenu is equal before and after caret icon, making difficult to scan the navigation labels.

### Why

The space between a label and icon of a single nav item should be minor than two different nav items.

See the screen attached.

![User Status=Login, Navigation=Megamenu + Link, Color=Primary](https://github.com/italia/design-ui-kit/assets/69706/bc027bc3-1206-4e64-9e08-a2a745640293)

**Comment by Fupete** [comment]
@zetareticoli the version on Bootstrap Italia developed (the same used in Designers Italia website) had already been fixed.

**Comment by zetareticoli** [comment]
Thanks @Fupete , we could apply the same fix here

**Comment by zetareticoli** [comment]
Resolved in [v3.6.0](https://github.com/italia/design-ui-kit/releases/tag/v3.6.0)
