### ISSUE TITLE
Stile serif-semibold-lg con font errato

### ISSUE THREAD

**Issue by ilbassa** [italia/design-ui-kit#130]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Allo stile "serif-semibold-lg" è associato il font "Titillium web", mentre tutti gli stili "Serif" sono associati al font "Lora"

### Perché

La definizione del font non è coerente con il resto delle definizioni "serif"

**Comment by Fupete** [comment]
✅ Corretto nel [rilascio v3.5.0 ](https://github.com/italia/design-ui-kit/releases/tag/v3.5.0) cc @ilbassa @zetareticoli
