### ISSUE TITLE
Componente `avatar` - Nella variante con testo il Link deve essere sottolineato

### ISSUE THREAD

**Issue by Fupete** [italia/design-ui-kit#134]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Il componente Avatar, nella variante con testo (nome utente o nickname ad es.), se cliccabile il link deve essere sottolinato. 

Il solo **bold** oltre il colore non basta a distinguere il link dal testo semplice. 
C'è infatti la possibilità di essere in un contesto dove l'avatar non sia chiaramente identificabile come item di menu e, inoltre, non si può escludere la presenza di alcuni nomi avatar cliccabili ed altri no nello stesso contesto.

### Perché

Visivamente accessibile.

### Contesto

Verifiche di accessibilità sui componenti.

Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

### Altro

Una volta risolto in problema in UI Kit Italia andranno uniformati i kit di sviluppo Bootstrap Italia e React. Al momento in Angular kit la variante con testo non è disponibile.

**Comment by Fupete** [comment]
cc @frmascia11y @astagi @zetareticoli

**Comment by zetareticoli** [comment]
Resolved in https://github.com/italia/design-ui-kit/commit/75d3b3c4a6e8b63f77871096c8ddbc4a6d6e2a02
