### ISSUE TITLE
Refinement Bottoni

### ISSUE THREAD

**Issue by matteodesanti** [italia/design-ui-kit#14]
- [x] ipotesi per verisoni dark
- [x] formalizzare padding e margini
- [x] gruppi orizzontali e verticali
- [x] versioni large & small
- [x] label + buttons

**Comment by matteodesanti** [comment]
Come promemoria da valutare anche tab+icona o bottoni verticali
Ad esempio così
![cursor_and_digital-wallet-iphone_sketch](https://user-images.githubusercontent.com/8171284/35268212-cc327010-0028-11e8-9f0f-9d953f7e832c.png)

**Comment by francescozaia** [comment]
Rivedere padding dopo ridefinizione line-height variabile
