### ISSUE TITLE
Simboli in formato .svg o equivalente

### ISSUE THREAD

**Issue by nferruzzi** [italia/design-ui-kit#2]
Penso aiuterebbe avere un formato oltre al file .sketch come riferimento per chi non usa Sketch
grazie

**Comment by nikorobins** [comment]
dunque si è scelto sketch perchè puoi gestire e creare gli elementi che ti servono in modo sistematico. Da una base di qualche decina di simboli puoi creare molteplici variazioni di uno stesso elemento in base al design che stai costruendo. Basta scegliere tra gli overrides le varianti disponibili. Se hai qualche programma da suggerire sarei interessata ad analizzare proposte e scambiare opinioni.
Grazie

**Comment by nferruzzi** [comment]
Grazie per la risposta e l'invito al dialogo :-) allora la mia richiesta nasce dal fatto che sketch e' pur sempre un tool mono piattaforma e pure a pagamento (questo come praticamente tutti i tool seri). Pero' sia chiaro che non volevo entrare nel merito del vostro flusso di lavoro .. ovviamente usate i tool che ritenete opportuni :) Quello che chiedevo all'atto pratico e' se vi e' possibile esportare i simboli e gli esempi in formati diversi (.svg piuttosto che png) in modo che siano visualizzabili e disponibili senza acquistare sketch. Grazie ancora
