### ISSUE TITLE
Probabile Mistyping | BOOTSTRAP GRID SYSTEM \ SMALL 

### ISSUE THREAD

**Issue by ValerioPinna** [italia/design-ui-kit#52]
Scrivo per segnalare che nell'ultimo file Sketch https://github.com/italia/design-ui-kit/blob/master/italia%20UI%20Kit%202.0.sketch 
c'è un piccolo mistyping riguardo BOOTSTRAP GRID SYSTEM \ SMALL.
Nel wireframe sono rappresentate 6 colonne ma nella guida ne vengono indicate 12.

**Comment by ValerioPinna** [comment]
Ciao Daniela

grazie mille per la risposta. 
Mi riferivo però a qualcosa di più semplice. 
Un probabile errore di scrittura all'interno del file Sketch. Ti allego lo screen per spiegarmi. 
<img width="400" alt="schermata 2018-05-10 alle 17 58 28" src="https://user-images.githubusercontent.com/29453383/39879779-06fd0ae6-547c-11e8-91b7-68d9b1a1f34e.png">


Come vedi vengono mostrate le indicazioni in SMALL TABLET (sotto la categoria BOOTSTAP GRID nella pagina GRID SYSTEM del file Sketch). 
Evidentemente le colonne sono 6 ma nella lablel poco sopra il wireframe c'è scritto 12. 
E' probabilmente un errore di battitura, niente di che :)

**Comment by nikorobins** [comment]
Ah ok Valerio
perdonami. Si è un modo di rappresentare la griglia di Bootstrap, per una questione di comodità lato design. Visto che ha un gutter costante di 30 px a qualsiasi risoluzione, ci si ritrova nelle risoluzioni small ad avere un'ampiezza di colonna inferiore al gutter.

**Comment by nikorobins** [comment]
Valerio, ho scritto un riquadro di approfondimento nel file master per spiegare l'accorpamento delle colonne, perchè come hai giustamente fatto notare potrebbe creare confusione.
Grazie per la segnalazione 👍 
Daniela
