### ISSUE TITLE
Errorino di ortografia

### ISSUE THREAD

**Issue by gianvitofanelli** [italia/design-ui-kit#57]
Ciao, volevo segnalarvi che nelle grid di Sketch c'è un piccolo typo. C'è scritto "breackpoint" invece di "breakpoint".

![screenshot 2018-06-04 12 59 58](https://user-images.githubusercontent.com/30351061/40914135-4ce80766-67f7-11e8-9c69-0b34508c0a38.jpg)

![screenshot 2018-06-04 13 02 30](https://user-images.githubusercontent.com/30351061/40914202-8f627e64-67f7-11e8-9302-2f77b905cb99.jpg)

**Comment by nikorobins** [comment]
Ciao, grazie per la segnalazione, correggo subito :-)
