### ISSUE TITLE
This share link cannot be viewed because this project is over quota.

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-ui-kit#74]
Segnalo:

https://projects.invisionapp.com/share/RJFGS2UC3HS

Over quota!
This share link cannot be viewed because this project is over quota.

**Comment by nikorobins** [comment]
Ciao Alessandro,
si stiamo rinnovando la licenza di Invision speriamo che la cosa si risolva in tempi brevi :-). Grazie comunque per la segnalazione.
